name: Windows MSYS2 Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          pacboy: >-
            toolchain:p ninja:p cmake:p extra-cmake-modules:p
            jasper:p icoutils:p
            qt6:p libopenmpt:p portaudio:p
      - name: Build pineapple-tracker-player
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX="package_workspace" -G Ninja
          cmake --build . -j
          cmake --build . --target install/strip
      - name: Prepare for package
        run: |
          cd build/package_workspace/bin
          ldd ./pineapple-tracker-player-quick.exe > deps-trackerplayer.txt
          bash -c 'while read -r line; do path=$(cut -d" " -f3 <<<$line); cp -v $path ./; done <<<$(grep ".*mingw.*bin" deps-trackerplayer.txt); exit 0'
          windeployqt6 --no-translations --no-opengl-sw --no-system-d3d-compiler ./pineapple-tracker-player-quick.exe
          windeployqt6 --no-quick-import --no-translations --no-opengl-sw --no-system-d3d-compiler ./pineapple-tracker-player.exe
          # rm deps-trackerplayer.txt
          # done
          cd ../../
      - uses: actions/upload-artifact@v4
        with:
          name: msys2-mingw-w64-x86_64-windows
          path: build/package_workspace/*
