name: Windows MSYS2 Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          pacboy: >-
            toolchain:p ninja:p cmake:p extra-cmake-modules:p
            jasper:p icoutils:p
            qt6-static:p libopenmpt:p portaudio:p
      - name: Build pineapple-tracker-player
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH="${MINGW_PREFIX}/qt6-static" -DCMAKE_INSTALL_PREFIX="package_workspace" -G Ninja
          cmake --build . -j
          cmake --build . --target install/strip
      - name: Prepare for package
        run: |
          rm -rf /c/Windows/SYSTEM32/libssl-* || true
          rm -rf /c/Windows/SYSTEM32/libcrypto-* || true
          cd build/package_workspace/bin
          ldd ./pineapple-tracker-player-quick.exe > deps-trackerplayer.txt
          bash -c 'while read -r line; do path=$(cut -d" " -f3 <<<$line); cp -v $path ./; done <<<$(grep ".*mingw.*bin" deps-trackerplayer.txt); exit 0'
          # rm deps-trackerplayer.txt
          # done
          cd ../../
      - uses: actions/upload-artifact@v3
        with:
          name: msys2-mingw-w64-x86_64-windows
          path: build/package_workspace/*
